/// Lista oficjalnych nazw torów (i układów) Gran Turismo 7 — do wyboru przy
/// „Nazwij tor".
///
/// Źródło: lista torów GT7 z Gran Turismo Wiki
/// (https://gran-turismo.fandom.com/wiki/Gran_Turismo_7/Track_List).
///
/// UWAGA: telemetria GT7 (formaty A/B/~) NIE zawiera ID toru, więc nazwy nie da
/// się przypisać automatycznie z pakietu — tor rozpoznajemy po obrysie śladu, a
/// nazwę użytkownik wybiera raz z tej listy. Wariant „odwrotny" ma ten sam obrys
/// co normalny, więc dopasowanie po obrysie ich nie rozróżni (można nazwać ręcznie).
library;

const List<String> gt7TrackNames = [
  'Alsace - Village',
  'Alsace - Test Course',
  'Autodrome Lago Maggiore - Full Course',
  'Autodrome Lago Maggiore - Centre',
  'Autodrome Lago Maggiore - East End',
  'Autodrome Lago Maggiore - West End',
  'Autodrome Lago Maggiore - East',
  'Autodrome Lago Maggiore - West',
  'Autódromo de Interlagos',
  'Autodromo Nazionale Monza',
  'Autodromo Nazionale Monza - No Chicane',
  'Autopolis International Racing Course',
  'Autopolis - Shortcut Course',
  'Blue Moon Bay Speedway',
  'Blue Moon Bay Speedway - Infield A',
  'Blue Moon Bay Speedway - Infield B',
  'Brands Hatch - Grand Prix Circuit',
  'Brands Hatch - Indy Circuit',
  'Broad Bean Raceway',
  'Circuit de Barcelona-Catalunya - Grand Prix',
  'Circuit de Barcelona-Catalunya - Grand Prix No Chicane',
  'Circuit de Barcelona-Catalunya - National',
  'Circuit de Barcelona-Catalunya - Rallycross',
  'Circuit de Sainte-Croix - A',
  'Circuit de Sainte-Croix - B',
  'Circuit de Sainte-Croix - C',
  'Circuit de Spa-Francorchamps',
  'Circuit de Spa-Francorchamps - 24h Layout',
  'Circuit Gilles-Villeneuve',
  'Colorado Springs - Lake',
  'Daytona International Speedway - Tri-Oval',
  'Daytona International Speedway - Road Course',
  'Deep Forest Raceway',
  'Dragon Trail - Seaside',
  'Dragon Trail - Gardens',
  'Eiger Nordwand',
  'Fishermans Ranch',
  'Fuji International Speedway',
  'Fuji International Speedway - Short Course',
  'Goodwood Motor Circuit',
  'Grand Valley - Highway 1',
  'Grand Valley - South',
  'High Speed Ring',
  'Kyoto Driving Park - Yamagiwa',
  'Kyoto Driving Park - Miyabi',
  'Kyoto Driving Park - Yamagiwa + Miyabi',
  'Lake Louise - Tri-Oval',
  'Lake Louise - Short Track',
  'Lake Louise - Long Track',
  'Michelin Raceway Road Atlanta',
  'Mount Panorama Circuit',
  'Northern Isle Speedway',
  'Nürburgring - Nordschleife',
  'Nürburgring - Nordschleife Tourist',
  'Nürburgring - Grand Prix',
  'Nürburgring - Endurance (24h)',
  'Nürburgring - Sprint',
  'Red Bull Ring',
  'Red Bull Ring - Short Track',
  'Sardegna - Road Track A',
  'Sardegna - Road Track B',
  'Sardegna - Road Track C',
  'Sardegna - Windmills',
  'Special Stage Route X',
  'Suzuka Circuit',
  'Suzuka Circuit - East Course',
  'Tokyo Expressway - Central Clockwise',
  'Tokyo Expressway - Central Counterclockwise',
  'Tokyo Expressway - East Clockwise',
  'Tokyo Expressway - East Counterclockwise',
  'Tokyo Expressway - South Clockwise',
  'Tokyo Expressway - South Counterclockwise',
  'Trial Mountain Circuit',
  'Tsukuba Circuit',
  'Watkins Glen International - Long Course',
  'Watkins Glen International - Short Course',
  'WeatherTech Raceway Laguna Seca',
  'Willow Springs - Big Willow',
  'Willow Springs - Streets of Willow Springs',
  'Willow Springs - Horse Thief Mile',
];
