// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAao4QBlmJsrx3OOHdnj6po_kJlobvnw5Q',
    appId: '1:629720470529:web:5abcf7952bbe0e73735c00',
    messagingSenderId: '629720470529',
    projectId: 'gt7-engineer',
    authDomain: 'gt7-engineer.firebaseapp.com',
    storageBucket: 'gt7-engineer.firebasestorage.app',
    measurementId: 'G-ZWY67CD13T',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwAq7TYdCXWVN0OBmvv1Wm4YhwU8_wfOQ',
    appId: '1:629720470529:ios:c68b86f70bf1d352735c00',
    messagingSenderId: '629720470529',
    projectId: 'gt7-engineer',
    storageBucket: 'gt7-engineer.firebasestorage.app',
    androidClientId: '629720470529-esdb9hja6h59v9u9cgq0juan9m536bus.apps.googleusercontent.com',
    iosClientId: '629720470529-d61cptk7b827hqk44qhp3qj4tuml7vcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gt7EngineerMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyurCS0vZAB290OkPm2PXmvBCqHkd5RJw',
    appId: '1:629720470529:android:d78cdac34fb6273d735c00',
    messagingSenderId: '629720470529',
    projectId: 'gt7-engineer',
    storageBucket: 'gt7-engineer.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAao4QBlmJsrx3OOHdnj6po_kJlobvnw5Q',
    appId: '1:629720470529:web:1416d30660ab8266735c00',
    messagingSenderId: '629720470529',
    projectId: 'gt7-engineer',
    authDomain: 'gt7-engineer.firebaseapp.com',
    storageBucket: 'gt7-engineer.firebasestorage.app',
    measurementId: 'G-1DP3MTTV3P',
  );
}
